[package]
name = "db"
version = "0.1.0"
authors = ["Akbar Taufiq Herlangga <angga@atherlangga.com>"]

[dependencies]
rustyline = "1.0.0"
scan_fmt = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
